print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("HEllo")
print("Hello Pallavi")
print("Hello Sagar")
print("Hello Sanket")
